name: sar-pinn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - netcdf4
  - scipy
  - matplotlib
  - cartopy
  - scikit-learn
  - pytorch
  - pip
  - pip:
      - jax
      - jaxlib
      - tqdm
      - pyyaml
